.TH "OBS-IMG-UTILS DOWNLOAD" "1" "10-Jul-2019" "" "obs-img-utils download Manual"
.SH NAME
obs-img-utils\-download \- Download image from Open Build Service at...
.SH SYNOPSIS
.B obs-img-utils download
[OPTIONS]
.SH DESCRIPTION
Download image from Open Build Service at `download_url`.
.SH OPTIONS
.TP
\fB\-\-conditions\fP
Invoke conditions process to specify conditions for image
.TP
\fB\-\-conditions\-wait\-time\fP INTEGER
Time (in seconds) to wait for conditions to be met. Retry period is 150 seconds and default is 0 seconds for no wait.
.TP
\fB\-C,\fP \-\-config PATH
Image Downloader config file to use. Default: ~/.config/obs_img_utils/config.yaml
.TP
\fB\-\-no\-color\fP
Remove ANSI color and styling from output.
.TP
\fB\-\-debug\fP
Display debug level logging to console.
.TP
\fB\-\-verbose\fP
Display logging info to console. (Default)
.TP
\fB\-\-quiet\fP
Disable console output.
.TP
\fB\-\-download\-url\fP TEXT
OBS download URL.
.TP
\fB\-\-download\-dir\fP PATH
Directory to store downloaded images and checksums.
.TP
\fB\-\-image\-name\fP TEXT
Image name from the OBS download URL.  [required]
.TP
\fB\-\-cloud\fP [azure|ec2|gce|oci]
Cloud framework for the image to be downloaded.
.TP
\fB\-\-arch\fP [x86_64|aarch64]
Architecture of the image.
.TP
\fB\-\-version\-format\fP TEXT
Version format for image. Should contain format strings for {kiwi_version} and {obs_build}. Example: "{kiwi_version}-Build{obs_build}".
