.TH "OBS-IMG-UTILS PACKAGES" "1" "2025-05-19" "1.8.0" "obs-img-utils packages Manual"
.SH NAME
obs-img-utils\-packages \- Package commands.
.SH SYNOPSIS
.B obs-img-utils packages
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
.PP
    Package commands.
    
.SH COMMANDS
.PP
\fBlist\fP
  Return a list of packages for the given...
  See \fBobs-img-utils packages-list(1)\fP for full documentation on the \fBlist\fP command.
.PP
\fBshow\fP
  Return information for the provided...
  See \fBobs-img-utils packages-show(1)\fP for full documentation on the \fBshow\fP command.
