.TH "OBS-IMG-UTILS" "1" "2025-05-19" "1.8.0" "obs-img-utils Manual"
.SH NAME
obs-img-utils \- The command line interface provides obs...
.SH SYNOPSIS
.B obs-img-utils
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
.PP
    The command line interface provides obs image utilities.
.PP
    This includes downloading images, checking packages in images
    and getting package version information.
    
.SH OPTIONS
.TP
\fB\-\-version\fP
Show the version and exit.
.TP
\fB\-\-license\fP
Show license information.
.SH COMMANDS
.PP
\fBdownload\fP
  Download image from OBS repository...
  See \fBobs-img-utils-download(1)\fP for full documentation on the \fBdownload\fP command.
.PP
\fBpackages\fP
  Package commands.
  See \fBobs-img-utils-packages(1)\fP for full documentation on the \fBpackages\fP command.
