.TH "OBS-IMG-UTILS" "1" "10-Jul-2019" "" "obs-img-utils Manual"
.SH NAME
obs-img-utils \- The command line interface allows you to...
.SH SYNOPSIS
.B obs-img-utils
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
The command line interface allows you to download and check OBS images.
.SH OPTIONS
.TP
\fB\-\-version\fP
Show the version and exit.
.TP
\fB\-\-license\fP
Show license information.
.SH COMMANDS
.PP
\fBdownload\fP
  Download image from Open Build Service at...
  See \fBobs-img-utils-download(1)\fP for full documentation on the \fBdownload\fP command.
.PP
\fBpackages\fP
  Handle package requests.
  See \fBobs-img-utils-packages(1)\fP for full documentation on the \fBpackages\fP command.
